### ISSUE TITLE
Apply Dependency Inversion Principle in User Class

### ISSUE THREAD

**Issue by zaynabtariq** [AgLyx3/Group-Sprint-1-Bookazon#6]
Refactor the User class so that it follows the Dependency Inversion Principle in the Cart creation process.

**Comment by cathymonkey** [comment]
**Description**:

The constructor of the ```User``` class violates the Dependency inversion principle as it intializes ```Cart``` in its constructor.  This is a tight coupling with ```Cart``` class because in the future, if we want to modify the ```Cart``` class, then we also need to change in the ```User``` class. 

Code snippet:

```.java
public User(String name, Subscription subscription) {
        this.name = name;
        this.subscription = subscription;  // normal, gold, platinum, silver membership
        this.cart = new Cart();
        this.orders = new ArrayList<>();
    }

```

**Suggested Solution**:
We are going to pass ```Cart``` as a parameter to the constructor. 
```.java
public User(String name, Subscription subscription, Cart cart) 
```

**Comment by AgLyx3** [comment]
Could you also check the testing in the Bookazon class (lines 78-79)? Thank you!

**Comment by cathymonkey** [comment]
Yes will do.
```.java
// create users
bookazon.addUser(new User("Alice", new NormalSubscription(), new Cart()));
bookazon.addUser(new User("Bob", new GoldSubscription(), new Cart()));

```
